[build]
  publish = "dist"
  command = "pnpm generate"

[build.environment]
  NODE_VERSION = "22.20.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://github.com/.*"]
