[build]
  publish = "dist"
  command = "pnpm generate"
  ignore = "! git log -1 --pretty=format:'%an' | grep -q 'ClemCornet'"

[build.environment]
  NODE_VERSION = "22.20.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://github.com/.*"]
